# import re


# s = f"""✅ Prompts saved to '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/Fighting_class_1_cmd.txt'
# Running first command in group 1: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_0_Mixed_q0/Test_0_Mixed_frame_6420.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What kind of direct physical violence is depicted in this scene? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Hugging'"'"', '"'"'Fighting'"'"', '"'"'Waving'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: Fighting
# Running first command in group 2: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_0_Mixed_q2/Test_0_Mixed_frame_7308.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: Which type of aggressive hand-to-hand action does this video illustrate? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Fighting'"'"', '"'"'Dancing'"'"', '"'"'Sitting'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: The video illustrates a type of aggressive hand-to-hand action that can be described as "Fighting." The silhouette and motion blur suggest dynamic movement, typically associated with combat or physical altercations.
# Running first command in group 3: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_0_Mixed_q3/Test_0_Mixed_frame_5575.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: This video shows a person engaging in what kind of violent activity? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Sleeping'"'"', '"'"'Fighting'"'"', '"'"'Walking'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: Fighting
# Running first command in group 4: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_1_Mixed_q4/Test_1_Mixed_frame_6873.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What violent behavior involving physical confrontation is shown in this video? Your candidate answer is as follows: ['"'"'Fighting'"'"', '"'"'Shooting'"'"', '"'"'Running'"'"', '"'"'Standing'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: Fighting
# Running first command in group 5: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_1_Mixed_q6/Test_1_Mixed_frame_5684.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: This video shows a person engaging in what kind of violent activity? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Sleeping'"'"', '"'"'Fighting'"'"', '"'"'Walking'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: Shooting
# Running first command in group 6: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_1_Mixed_q7/Test_1_Mixed_frame_4525.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What kind of direct physical violence is depicted in this scene? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Hugging'"'"', '"'"'Fighting'"'"', '"'"'Waving'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: Fighting
# Running first command in group 7: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_2_Mixed_q8/Test_2_Mixed_frame_6264.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What violent behavior involving physical confrontation is shown in this video? Your candidate answer is as follows: ['"'"'Fighting'"'"', '"'"'Shooting'"'"', '"'"'Running'"'"', '"'"'Standing'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: Fighting
# Running first command in group 8: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_2_Mixed_q10/Test_2_Mixed_frame_4704.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What kind of direct physical violence is depicted in this scene? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Hugging'"'"', '"'"'Fighting'"'"', '"'"'Waving'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 9: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_2_Mixed_q11/Test_2_Mixed_frame_5249.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: Which type of aggressive hand-to-hand action does this video illustrate? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Fighting'"'"', '"'"'Dancing'"'"', '"'"'Sitting'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 10: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_3_Mixed_q12/Test_3_Mixed_frame_7540.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What violent behavior involving physical confrontation is shown in this video? Your candidate answer is as follows: ['"'"'Fighting'"'"', '"'"'Shooting'"'"', '"'"'Running'"'"', '"'"'Standing'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 11: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_3_Mixed_q14/Test_3_Mixed_frame_6728.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: This video shows a person engaging in what kind of violent activity? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Sleeping'"'"', '"'"'Fighting'"'"', '"'"'Walking'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: Fighting
# Running first command in group 12: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_3_Mixed_q15/Test_3_Mixed_frame_4536.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What kind of direct physical violence is depicted in this scene? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Hugging'"'"', '"'"'Fighting'"'"', '"'"'Waving'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 13: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_4_Mixed_q16/Test_4_Mixed_frame_5597.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: Which type of aggressive hand-to-hand action does this video illustrate? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Fighting'"'"', '"'"'Dancing'"'"', '"'"'Sitting'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: Fighting
# Running first command in group 14: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_4_Mixed_q18/Test_4_Mixed_frame_5750.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What violent behavior involving physical confrontation is shown in this video? Your candidate answer is as follows: ['"'"'Fighting'"'"', '"'"'Shooting'"'"', '"'"'Running'"'"', '"'"'Standing'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: Fighting
# Running first command in group 15: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_4_Mixed_q19/Test_4_Mixed_frame_5184.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What kind of direct physical violence is depicted in this scene? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Hugging'"'"', '"'"'Fighting'"'"', '"'"'Waving'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 16: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_5_Mixed_q20/Test_5_Mixed_frame_7250.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: Which type of aggressive hand-to-hand action does this video illustrate? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Fighting'"'"', '"'"'Dancing'"'"', '"'"'Sitting'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: The video illustrates a type of aggressive hand-to-hand action that can be described as 'Fighting'. The rapid and intense movements, along with the presence of dust clouds, suggest a physical struggle or combat scenario. While there is no clear evidence of shooting or dancing, the nature of the actions being performed aligns most closely with fighting.
# Running first command in group 17: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_5_Mixed_q22/Test_5_Mixed_frame_5481.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What kind of direct physical violence is depicted in this scene? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Hugging'"'"', '"'"'Fighting'"'"', '"'"'Waving'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: Shooting
# Running first command in group 18: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_5_Mixed_q23/Test_5_Mixed_frame_7134.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What violent behavior involving physical confrontation is shown in this video? Your candidate answer is as follows: ['"'"'Fighting'"'"', '"'"'Shooting'"'"', '"'"'Running'"'"', '"'"'Standing'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: The violent behavior involving physical confrontation shown in this video is 'Fighting'.
# Running first command in group 19: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_6_Mixed_q24/Test_6_Mixed_frame_7279.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What kind of direct physical violence is depicted in this scene? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Hugging'"'"', '"'"'Fighting'"'"', '"'"'Waving'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: Fighting
# Running first command in group 20: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_6_Mixed_q26/Test_6_Mixed_frame_6192.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: This video shows a person engaging in what kind of violent activity? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Sleeping'"'"', '"'"'Fighting'"'"', '"'"'Walking'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: The video shows a person engaging in 'fighting' activity, as evident by the aggressive stance and motion towards another individual.
# Running first command in group 21: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_6_Mixed_q27/Test_6_Mixed_frame_6216.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What violent behavior involving physical confrontation is shown in this video? Your candidate answer is as follows: ['"'"'Fighting'"'"', '"'"'Shooting'"'"', '"'"'Running'"'"', '"'"'Standing'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: Fighting
# Running first command in group 22: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_7_Mixed_q28/Test_7_Mixed_frame_5928.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: Which type of aggressive hand-to-hand action does this video illustrate? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Fighting'"'"', '"'"'Dancing'"'"', '"'"'Sitting'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 23: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_7_Mixed_q30/Test_7_Mixed_frame_5856.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What kind of direct physical violence is depicted in this scene? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Hugging'"'"', '"'"'Fighting'"'"', '"'"'Waving'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 24: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_7_Mixed_q31/Test_7_Mixed_frame_5448.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What violent behavior involving physical confrontation is shown in this video? Your candidate answer is as follows: ['"'"'Fighting'"'"', '"'"'Shooting'"'"', '"'"'Running'"'"', '"'"'Standing'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 25: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_8_Mixed_q32/Test_8_Mixed_frame_4632.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What violent behavior involving physical confrontation is shown in this video? Your candidate answer is as follows: ['"'"'Fighting'"'"', '"'"'Shooting'"'"', '"'"'Running'"'"', '"'"'Standing'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: Fighting
# Running first command in group 26: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_8_Mixed_q34/Test_8_Mixed_frame_4728.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: This video shows a person engaging in what kind of violent activity? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Sleeping'"'"', '"'"'Fighting'"'"', '"'"'Walking'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: Shooting
# Running first command in group 27: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_8_Mixed_q35/Test_8_Mixed_frame_4525.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: Which type of aggressive hand-to-hand action does this video illustrate? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Fighting'"'"', '"'"'Dancing'"'"', '"'"'Sitting'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: The video appears to illustrate a type of aggressive hand-to-hand action. Based on the images provided, the most appropriate answer from the given candidates would be 'Fighting'. The intensity and physical nature of the interaction suggest it is not simply dancing or sitting, and while there could be elements of shooting, the primary focus seems to be on physical confrontation between individuals.
# Running first command in group 28: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_9_Mixed_q36/Test_9_Mixed_frame_5520.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What kind of direct physical violence is depicted in this scene? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Hugging'"'"', '"'"'Fighting'"'"', '"'"'Waving'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 29: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_9_Mixed_q38/Test_9_Mixed_frame_4344.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: Which type of aggressive hand-to-hand action does this video illustrate? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Fighting'"'"', '"'"'Dancing'"'"', '"'"'Sitting'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 30: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_9_Mixed_q39/Test_9_Mixed_frame_4656.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What violent behavior involving physical confrontation is shown in this video? Your candidate answer is as follows: ['"'"'Fighting'"'"', '"'"'Shooting'"'"', '"'"'Running'"'"', '"'"'Standing'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: Fighting
# Running first command in group 31: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_10_Mixed_q40/Test_10_Mixed_frame_5520.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: This video shows a person engaging in what kind of violent activity? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Sleeping'"'"', '"'"'Fighting'"'"', '"'"'Walking'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 32: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_10_Mixed_q42/Test_10_Mixed_frame_5856.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: Which type of aggressive hand-to-hand action does this video illustrate? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Fighting'"'"', '"'"'Dancing'"'"', '"'"'Sitting'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: Fighting
# Running first command in group 33: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_10_Mixed_q43/Test_10_Mixed_frame_5928.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What kind of direct physical violence is depicted in this scene? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Hugging'"'"', '"'"'Fighting'"'"', '"'"'Waving'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 34: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_11_Mixed_q44/Test_11_Mixed_frame_4488.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What kind of direct physical violence is depicted in this scene? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Hugging'"'"', '"'"'Fighting'"'"', '"'"'Waving'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 35: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_11_Mixed_q46/Test_11_Mixed_frame_5423.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: This video shows a person engaging in what kind of violent activity? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Sleeping'"'"', '"'"'Fighting'"'"', '"'"'Walking'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: Fighting
# Running first command in group 36: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_11_Mixed_q47/Test_11_Mixed_frame_5736.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What violent behavior involving physical confrontation is shown in this video? Your candidate answer is as follows: ['"'"'Fighting'"'"', '"'"'Shooting'"'"', '"'"'Running'"'"', '"'"'Standing'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 37: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_12_Mixed_q48/Test_12_Mixed_frame_5481.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What kind of direct physical violence is depicted in this scene? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Hugging'"'"', '"'"'Fighting'"'"', '"'"'Waving'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 38: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_12_Mixed_q50/Test_12_Mixed_frame_7540.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: Which type of aggressive hand-to-hand action does this video illustrate? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Fighting'"'"', '"'"'Dancing'"'"', '"'"'Sitting'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: The video illustrates a type of aggressive hand-to-hand action known as 'Shooting'. The characters are engaged in combat, wielding firearms and engaging in what appears to be a firefight. This matches the description provided in the question, where shooting is explicitly mentioned as one of the options.
# Running first command in group 39: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_12_Mixed_q51/Test_12_Mixed_frame_5640.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: This video shows a person engaging in what kind of violent activity? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Sleeping'"'"', '"'"'Fighting'"'"', '"'"'Walking'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 40: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_13_Mixed_q52/Test_13_Mixed_frame_5452.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: Which type of aggressive hand-to-hand action does this video illustrate? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Fighting'"'"', '"'"'Dancing'"'"', '"'"'Sitting'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: The video illustrates 'Fighting' as the type of aggressive hand-to-hand action taking place. The individuals are engaged in a physical confrontation, which is evident from their positioning and gestures towards each other.
# Running first command in group 41: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_13_Mixed_q54/Test_13_Mixed_frame_5544.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What kind of direct physical violence is depicted in this scene? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Hugging'"'"', '"'"'Fighting'"'"', '"'"'Waving'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 42: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_13_Mixed_q55/Test_13_Mixed_frame_5544.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What violent behavior involving physical confrontation is shown in this video? Your candidate answer is as follows: ['"'"'Fighting'"'"', '"'"'Shooting'"'"', '"'"'Running'"'"', '"'"'Standing'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 43: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_14_Mixed_q56/Test_14_Mixed_frame_5365.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: This video shows a person engaging in what kind of violent activity? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Sleeping'"'"', '"'"'Fighting'"'"', '"'"'Walking'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 44: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_14_Mixed_q58/Test_14_Mixed_frame_5544.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What violent behavior involving physical confrontation is shown in this video? Your candidate answer is as follows: ['"'"'Fighting'"'"', '"'"'Shooting'"'"', '"'"'Running'"'"', '"'"'Standing'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: Fighting
# Running first command in group 45: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_14_Mixed_q59/Test_14_Mixed_frame_7772.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What kind of direct physical violence is depicted in this scene? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Hugging'"'"', '"'"'Fighting'"'"', '"'"'Waving'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 46: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_15_Mixed_q60/Test_15_Mixed_frame_7627.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: Which type of aggressive hand-to-hand action does this video illustrate? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Fighting'"'"', '"'"'Dancing'"'"', '"'"'Sitting'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: The video illustrates a type of aggressive hand-to-hand action that can be described as "Fighting." The individuals are seen engaging in close combat, suggesting a physical altercation rather than shooting or dancing.
# Running first command in group 47: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_15_Mixed_q62/Test_15_Mixed_frame_6902.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: This video shows a person engaging in what kind of violent activity? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Sleeping'"'"', '"'"'Fighting'"'"', '"'"'Walking'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: The video shows a person engaging in 'Shooting' activity. The presence of firearms and aggressive body language among the individuals suggests that they are involved in a violent altercation, which is consistent with shooting behavior.
# Running first command in group 48: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_15_Mixed_q63/Test_15_Mixed_frame_5365.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What kind of direct physical violence is depicted in this scene? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Hugging'"'"', '"'"'Fighting'"'"', '"'"'Waving'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 49: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_16_Mixed_q64/Test_16_Mixed_frame_7453.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What kind of direct physical violence is depicted in this scene? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Hugging'"'"', '"'"'Fighting'"'"', '"'"'Waving'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: The video contains a sequence of images depicting the physical transformation of an object, specifically a rifle. The process begins with a detailed illustration of the rifle in its initial state and transitions through various stages of disassembly or modification. As the frames progress, we observe the gradual breakdown of the rifle's components, leading to a final image that suggests either complete disassembly or a drastically altered form.

# Given this context, the most appropriate candidate answer from the list provided ('Shooting', 'Hugging', 'Fighting', 'Waving') is none. The video does not depict any direct physical violence; instead, it focuses on the manipulation and alteration of an object without inflicting harm or engaging in aggressive behavior.
# Running first command in group 50: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_16_Mixed_q66/Test_16_Mixed_frame_5575.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: This video shows a person engaging in what kind of violent activity? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Sleeping'"'"', '"'"'Fighting'"'"', '"'"'Walking'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: The video does not provide enough information to determine the specific violent activity being engaged in. Therefore, none of the candidates ('Shooting', 'Sleeping', 'Fighting', 'Walking') can be accurately identified from these frames.
# Running first command in group 51: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_16_Mixed_q67/Test_16_Mixed_frame_6420.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: Which type of aggressive hand-to-hand action does this video illustrate? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Fighting'"'"', '"'"'Dancing'"'"', '"'"'Sitting'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: Fighting
# Running first command in group 52: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_17_Mixed_q68/Test_17_Mixed_frame_6699.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: This video shows a person engaging in what kind of violent activity? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Sleeping'"'"', '"'"'Fighting'"'"', '"'"'Walking'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 53: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_17_Mixed_q70/Test_17_Mixed_frame_6960.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What kind of direct physical violence is depicted in this scene? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Hugging'"'"', '"'"'Fighting'"'"', '"'"'Waving'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 54: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_17_Mixed_q71/Test_17_Mixed_frame_5597.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: Which type of aggressive hand-to-hand action does this video illustrate? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Fighting'"'"', '"'"'Dancing'"'"', '"'"'Sitting'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: Fighting
# Running first command in group 55: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_18_Mixed_q72/Test_18_Mixed_frame_5520.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: Which type of aggressive hand-to-hand action does this video illustrate? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Fighting'"'"', '"'"'Dancing'"'"', '"'"'Sitting'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 56: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_18_Mixed_q74/Test_18_Mixed_frame_6931.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What violent behavior involving physical confrontation is shown in this video? Your candidate answer is as follows: ['"'"'Fighting'"'"', '"'"'Shooting'"'"', '"'"'Running'"'"', '"'"'Standing'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: Fighting
# Running first command in group 57: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_18_Mixed_q75/Test_18_Mixed_frame_5575.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What kind of direct physical violence is depicted in this scene? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Hugging'"'"', '"'"'Fighting'"'"', '"'"'Waving'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 58: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_19_Mixed_q76/Test_19_Mixed_frame_5520.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What kind of direct physical violence is depicted in this scene? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Hugging'"'"', '"'"'Fighting'"'"', '"'"'Waving'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 59: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_19_Mixed_q78/Test_19_Mixed_frame_6420.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What violent behavior involving physical confrontation is shown in this video? Your candidate answer is as follows: ['"'"'Fighting'"'"', '"'"'Shooting'"'"', '"'"'Running'"'"', '"'"'Standing'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: None
# Running first command in group 60: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_19_Mixed_q79/Test_19_Mixed_frame_5000.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: This video shows a person engaging in what kind of violent activity? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Sleeping'"'"', '"'"'Fighting'"'"', '"'"'Walking'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 61: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_20_Mixed_q80/Test_20_Mixed_frame_4944.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What violent behavior involving physical confrontation is shown in this video? Your candidate answer is as follows: ['"'"'Fighting'"'"', '"'"'Shooting'"'"', '"'"'Running'"'"', '"'"'Standing'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: Fighting
# Running first command in group 62: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_20_Mixed_q82/Test_20_Mixed_frame_4632.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What kind of direct physical violence is depicted in this scene? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Hugging'"'"', '"'"'Fighting'"'"', '"'"'Waving'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 63: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_20_Mixed_q83/Test_20_Mixed_frame_5160.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: Which type of aggressive hand-to-hand action does this video illustrate? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Fighting'"'"', '"'"'Dancing'"'"', '"'"'Sitting'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: The video illustrates a type of aggressive hand-to-hand action. Given the options provided, the most appropriate answer is 'Fighting'. The images depict close physical contact between individuals, with one person seemingly in control and exerting force on another. This aligns with the definition of fighting, which involves combat or violent struggle between people.
# Running first command in group 64: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_21_Mixed_q84/Test_21_Mixed_frame_5064.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: This video shows a person engaging in what kind of violent activity? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Sleeping'"'"', '"'"'Fighting'"'"', '"'"'Walking'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: Fighting
# Running first command in group 65: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_21_Mixed_q86/Test_21_Mixed_frame_5208.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: Which type of aggressive hand-to-hand action does this video illustrate? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Fighting'"'"', '"'"'Dancing'"'"', '"'"'Sitting'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: Fighting
# Running first command in group 66: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_21_Mixed_q87/Test_21_Mixed_frame_5616.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What violent behavior involving physical confrontation is shown in this video? Your candidate answer is as follows: ['"'"'Fighting'"'"', '"'"'Shooting'"'"', '"'"'Running'"'"', '"'"'Standing'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: Fighting
# Running first command in group 67: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_22_Mixed_q88/Test_22_Mixed_frame_7200.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: This video shows a person engaging in what kind of violent activity? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Sleeping'"'"', '"'"'Fighting'"'"', '"'"'Walking'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 68: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_22_Mixed_q90/Test_22_Mixed_frame_5448.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What violent behavior involving physical confrontation is shown in this video? Your candidate answer is as follows: ['"'"'Fighting'"'"', '"'"'Shooting'"'"', '"'"'Running'"'"', '"'"'Standing'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: Fighting
# Running first command in group 69: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_22_Mixed_q91/Test_22_Mixed_frame_5424.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: Which type of aggressive hand-to-hand action does this video illustrate? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Fighting'"'"', '"'"'Dancing'"'"', '"'"'Sitting'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: Fighting
# Running first command in group 70: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_23_Mixed_q92/Test_23_Mixed_frame_6438.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: Which type of aggressive hand-to-hand action does this video illustrate? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Fighting'"'"', '"'"'Dancing'"'"', '"'"'Sitting'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 71: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_23_Mixed_q94/Test_23_Mixed_frame_4848.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What kind of direct physical violence is depicted in this scene? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Hugging'"'"', '"'"'Fighting'"'"', '"'"'Waving'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 72: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_23_Mixed_q95/Test_23_Mixed_frame_6090.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: This video shows a person engaging in what kind of violent activity? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Sleeping'"'"', '"'"'Fighting'"'"', '"'"'Walking'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: None
# Running first command in group 73: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_24_Mixed_q96/Test_24_Mixed_frame_5184.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What violent behavior involving physical confrontation is shown in this video? Your candidate answer is as follows: ['"'"'Fighting'"'"', '"'"'Shooting'"'"', '"'"'Running'"'"', '"'"'Standing'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 74: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_24_Mixed_q98/Test_24_Mixed_frame_6989.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: Which type of aggressive hand-to-hand action does this video illustrate? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Fighting'"'"', '"'"'Dancing'"'"', '"'"'Sitting'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: The video illustrates a type of aggressive hand-to-hand action that falls under the category of 'Fighting'. The individuals are engaged in a physical altercation, which is evident from their postures and interactions. There is no indication of shooting or dancing behavior, and while sitting could be involved, it's not the focus of the action depicted in the frames provided. Therefore, the most accurate answer among the given candidates is 'Fighting'.
# Running first command in group 75: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_24_Mixed_q99/Test_24_Mixed_frame_5184.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What kind of direct physical violence is depicted in this scene? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Hugging'"'"', '"'"'Fighting'"'"', '"'"'Waving'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 76: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_25_Mixed_q100/Test_25_Mixed_frame_7163.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What violent behavior involving physical confrontation is shown in this video? Your candidate answer is as follows: ['"'"'Fighting'"'"', '"'"'Shooting'"'"', '"'"'Running'"'"', '"'"'Standing'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: The video depicts a scenario involving physical confrontation, which can be best described as 'Fighting'. The individual is shown in various poses that suggest aggressive actions or attempts to avoid contact. While the exact nature of the confrontation isn't clear from the images provided, the overall context implies a violent altercation rather than shooting or running. Therefore, the appropriate answer is: Fighting.
# Running first command in group 77: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_25_Mixed_q102/Test_25_Mixed_frame_4464.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What kind of direct physical violence is depicted in this scene? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Hugging'"'"', '"'"'Fighting'"'"', '"'"'Waving'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 78: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_25_Mixed_q103/Test_25_Mixed_frame_5664.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: This video shows a person engaging in what kind of violent activity? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Sleeping'"'"', '"'"'Fighting'"'"', '"'"'Walking'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 79: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_27_Mixed_q108/Test_27_Mixed_frame_5544.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: Which type of aggressive hand-to-hand action does this video illustrate? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Fighting'"'"', '"'"'Dancing'"'"', '"'"'Sitting'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 80: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_27_Mixed_q110/Test_27_Mixed_frame_5925.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What kind of direct physical violence is depicted in this scene? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Hugging'"'"', '"'"'Fighting'"'"', '"'"'Waving'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 81: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_27_Mixed_q111/Test_27_Mixed_frame_5256.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: This video shows a person engaging in what kind of violent activity? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Sleeping'"'"', '"'"'Fighting'"'"', '"'"'Walking'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 82: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_28_Mixed_q112/Test_28_Mixed_frame_6815.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: This video shows a person engaging in what kind of violent activity? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Sleeping'"'"', '"'"'Fighting'"'"', '"'"'Walking'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 83: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_28_Mixed_q114/Test_28_Mixed_frame_4968.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What kind of direct physical violence is depicted in this scene? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Hugging'"'"', '"'"'Fighting'"'"', '"'"'Waving'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: The kind of direct physical violence depicted in this scene is 'Fighting'. The individuals are engaged in a physical altercation, with one attempting to strike the other and then being struck back.
# Running first command in group 84: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_28_Mixed_q115/Test_28_Mixed_frame_4344.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: Which type of aggressive hand-to-hand action does this video illustrate? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Fighting'"'"', '"'"'Dancing'"'"', '"'"'Sitting'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: The video illustrates a type of aggressive hand-to-hand action. Based on the given options, 'Fighting' is the most appropriate candidate as it encompasses the aggressive interaction typically depicted in such scenarios.
# Running first command in group 85: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_29_Mixed_q116/Test_29_Mixed_frame_4950.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: What kind of direct physical violence is depicted in this scene? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Hugging'"'"', '"'"'Fighting'"'"', '"'"'Waving'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: Fighting
# Running first command in group 86: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_29_Mixed_q118/Test_29_Mixed_frame_5550.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: Which type of aggressive hand-to-hand action does this video illustrate? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Fighting'"'"', '"'"'Dancing'"'"', '"'"'Sitting'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# Running first command in group 87: /home/cxx/HWs/AKS/llama.cpp/llama-minicpmv-cli -m /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/ggml-model-Q4_K_M.gguf --mmproj /home/cxx/HWs/AKS/llama.cpp/Minicpmv2_6_gguf/mmproj-model-f16.gguf -c 4096 --temp 0.7 --top-p 0.8 --top-k 100 --repeat-penalty 1.05 --image '/home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/outputs/Fighting/class_1/jpgs/Test_29_Mixed_q119/Test_29_Mixed_frame_5394.jpg' -p 'You are a video checking expert, you will be given an image of video, you need to answer the following question: Q: This video shows a person engaging in what kind of violent activity? Your candidate answer is as follows: ['"'"'Shooting'"'"', '"'"'Sleeping'"'"', '"'"'Fighting'"'"', '"'"'Walking'"'"']. You need to answer the question by giving one of the candidates, like Fighting or Shooting. If you find there aren'"'"'t any answer can be found, you should give NONE as the answer.'
# result: NONE
# ✅ Results saved to /home/cxx/HWs/AKS/Mixed Video Pipeline/Testing/Fighting_class_1_res.txt"""

# results = re.findall(r'result: (.+)', s)

# # Process the results to extract the final answer
# print(len(results))
# # print("Final results:", results)
# extracted_answers = []

# for result in results:
#     # Use regular expressions to find the specific keywords
#     if re.search(r'\bFighting\b', result, re.IGNORECASE):
#         extracted_answers.append('Fighting')
#     elif re.search(r'\bShooting\b', result, re.IGNORECASE):
#         extracted_answers.append('Shooting')
#     elif re.search(r'\bNONE\b', result, re.IGNORECASE):
#         extracted_answers.append('NONE')
#     else:
#         extracted_answers.append("UNKNOWN")  # For any result that doesn't match
    
   
# print(extracted_answers)


# from mixed_strategy import VideoMixer
# import os

# if __name__ == "__main__":
#     Number = 30
#     class_type = 2
#     total_duration = 360
#     B_folder = "/home/cxx/HWs/AKS/datasets/XD_violence/ours/Benign/"

#     B_list = sorted([
#         os.path.join(B_folder, f)
#         for f in os.listdir(B_folder)
#         if f.endswith(".mp4")
#     ])[:Number]


#     M_list = [f"/home/cxx/HWs/AKS/datasets/XD_violence/ours/Fighting/Test_{i}_Fighting.mp4" for i in range(Number)]
#     O_list = [f"/home/cxx/HWs/AKS/Mixed Video Pipeline/outputs/class_2/Test_{i}_Mixed.mp4" for i in range(Number)]

#     for i in range(30):
#         print(f"[🚀] Processing sample Class {class_type}: {i}...")
#         print(f"[🤖] Benign video: {B_list[i]}, Malignant video: {M_list[i]}")
#         mixer = VideoMixer(
#             benign_video=B_list[i],
#             malignant_video=M_list[i],
#             output_path=O_list[i]
#         )
#         mixer.generate_mixed_video(class_type=class_type, total_duration=total_duration)


# import os
# import re

# def rename_videos(directory):
#     """
#     Rename video files in the specified directory from the format
#     'Test_i_Mixed_class1_360s.mp4' to 'Test_i_Mixed.mp4'.

#     Args:
#         directory (str): The directory containing the video files to rename.
#     """
#     # Regular expression to match the filename pattern
#     pattern = re.compile(r'(Test_\d+_Mixed)_class2_360s\.mp4')
#     i = 0
#     # List all files in the directory
#     for filename in os.listdir(directory):
#         i+=1
#         match = pattern.match(filename)
#         if match:
#             # Extract the new filename without the '_class1_360s' part
#             new_filename = f"{match.group(1)}.mp4"
#             # Construct the full paths for the old and new filenames
#             old_file_path = os.path.join(directory, filename)
#             new_file_path = os.path.join(directory, new_filename)
#             # Rename the file
#             os.rename(old_file_path, new_file_path)
#             print(f"Renamed '{filename}' to '{new_filename}'")
#         # if i==1:
#         #     break
# # Example usage
# if __name__ == "__main__":
#     video_directory = "/home/cxx/HWs/AKS/Mixed Video Pipeline/outputs/Shooting/class_2"
#     rename_videos(video_directory)




# import os
# import json

# def read_all_frame_jsons(folder_path, output_path=None):
#     merged_list = []

#     # 遍历所有 json 文件
#     for filename in os.listdir(folder_path):
#         if filename.endswith(".json") and filename.startswith("Test_") and "_Mixed_q" in filename:
#             file_path = os.path.join(folder_path, filename)
#             try:
#                 with open(file_path, 'r') as f:
#                     data = json.load(f)
#                     if isinstance(data, list):
#                         merged_list.append(data)
#                     else:
#                         print(f"⚠️ Skip non-list file: {filename}")
#             except Exception as e:
#                 print(f"❌ Failed to read {filename}: {e}")
#     with open(output_path, 'w') as f:
#         json.dump(merged_list, f)
#     print(f"✅ Merged {len(merged_list)} files to {output_path}")

#     return merged_list

# frames_dir = "/home/cxx/HWs/AKS/Mixed Video Pipeline/extracted_things/Shooting/class_2/blip/scores"
# output_path = "/home/cxx/HWs/AKS/Mixed Video Pipeline/extracted_things/Shooting/class_2/blip/scores.json"
# all_frames = read_all_frame_jsons(frames_dir, output_path)
# print(f"Total frames collected: {len(all_frames)}")


# frames_dir = "/home/cxx/HWs/AKS/Mixed Video Pipeline/extracted_things/Shooting/class_2/blip/frames"
# output_path = "/home/cxx/HWs/AKS/Mixed Video Pipeline/extracted_things/Shooting/class_2/blip/frames.json"
# all_frames = read_all_frame_jsons(frames_dir, output_path)
# print(f"Total frames collected: {len(all_frames)}")
# print(all_frames[:10])



# import json
# ori = "/home/cxx/HWs/AKS/Mixed Video Pipeline/extracted_things/Fighting/class_1/blip/selected_frames/selected_frames.json"
# opt = "/home/cxx/HWs/AKS/Mixed Video Pipeline/extracted_things/Fighting/class_1/blip/optimized_frames/optimized_frames.json"

# with open(ori, 'r') as f:
#     data_1 = json.load(f)

# with open(opt, 'r') as f:
#     data_2 = json.load(f)

# print(f"Number of samples in ori: {len(data_1)}")
# print(f"Number of samples in opt: {len(data_2)}")

# if len(data_1) != len(data_2):
#     print("❗Mismatch in number of samples.")
# else:
#     print("✅ Same number of samples.")


# diff_stats = []

# for i, (a, b) in enumerate(zip(data_1, data_2)):
#     set_a, set_b = set(a), set(b)
#     added = sorted(list(set_b - set_a))
#     removed = sorted(list(set_a - set_b))

#     if added or removed:
#         diff_stats.append({
#             "index": i,
#             "added": added,
#             "removed": removed
#         })

# print(f"\nTotal different entries: {len(diff_stats)}")


# for d in diff_stats[:5]:  # 打印前 5 个不同的样本
#     print(f"\nSample #{d['index']}")
#     print(f"  ➕ Added in opt: {d['added']}")
#     print(f"  ➖ Removed from ori: {d['removed']}")

    
# def jaccard(a, b):
#     a, b = set(a), set(b)
#     if not a and not b:
#         return 1.0
#     return len(a & b) / len(a | b)

# scores = [jaccard(a, b) for a, b in zip(data_1, data_2)]
# print(f"\nAverage frame overlap (Jaccard): {sum(scores)/len(scores):.4f}")
